### ISSUE TITLE
0.6.0 TACore throwing errors.

### ISSUE THREAD

**Issue by ThaNightHawk** [MatrikMoon/TournamentAssistant#40]
Updated to 0.6.0, and have gotten some random errors, just spamming the console. 
 - Using the auto-generated config, with only changing name, password, ip and the banned mods. Config-file was closed before launching server.

```
Wrong group was ended
   at ProtoBuf.ProtoReader.State.ThrowProtoException(String message)
   at ProtoBuf.ProtoReader.State.EndSubItem(SubItemToken token)
   at ProtoBuf.ProtoReader.State.ReadMessage[TSerializer,T](SerializerFeatures features, T value, TSerializer& serializer)
   at proto_2(State& , Packet )
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at TournamentAssistantShared.Utilities.ProtobufExtensions.ProtoDeserialize[T](Byte[] data)
   at TournamentAssistantShared.Sockets.WsServer.ReceiveLoop(ConnectedUser player)
```

```
Invalid wire-type (6); this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.State.ThrowProtoException(String message)
   at ProtoBuf.ProtoReader.State.ThrowWireTypeException()
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState)
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState)
   at ProtoBuf.ProtoReader.State.AppendExtensionData(IExtensible instance)
   at proto_74(State& , SendBotMessage )
   at ProtoBuf.ProtoReader.State.ReadMessage[TSerializer,T](SerializerFeatures features, T value, TSerializer& serializer)
   at proto_2(State& , Packet )
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at TournamentAssistantShared.Utilities.ProtobufExtensions.ProtoDeserialize[T](Byte[] data)
   at TournamentAssistantShared.Sockets.WsServer.ReceiveLoop(ConnectedUser player)
```

When looking at websocket data, it returns a stringy mess, when looking at it. Both unicode filtered:
```
$342f7525-061f-46f1-9555-81832df8f894$00000000-0000-0000-0000-000000000000R2*0.,$69a41d72-8ec4-4972-964d-fd462908b80aCoordinator
```
and none-filtered:
```
$342f7525-061f-46f1-9555-81832df8f894$00000000-0000-0000-0000-000000000000R2*0
.
,$69a41d72-8ec4-4972-964d-fd462908b80aCoordinator
```

**Comment by MatrikMoon** [comment]
Wow! Stringy mess indeed! This appears to be a websocket error, and I have some plans to re-work websocket support. I will reach out to you (or, you're free to reach out to me if I take too long) before the next update to see if the rework fixes your problem

**Comment by ThaNightHawk** [comment]
Hiya, I am back! 

I have no idea if this is useful, but I want to inform you about it anyways, just in-case.

I don't know what caused those errors to pop up. I've used the stream sync function, but I haven't looked in the server-console while the server was running, to prevent any interference that could happen.
```
Attempted to read past the end of the stream.
   at ProtoBuf.ProtoReader.State.ThrowEoF()
   at ProtoBuf.ProtoReader.StreamProtoReader.ImplReadUInt32Fixed(State& state)
   at ProtoBuf.ProtoReader.State.AppendExtensionField(State& writeState)
   at ProtoBuf.ProtoReader.State.AppendExtensionData(IExtensible instance)
   at proto_2(State& , Packet )
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at TournamentAssistantShared.Utilities.ProtobufExtensions.ProtoDeserialize[T](Byte[] data)
   at TournamentAssistantShared.PacketWrapper.FromStream(MemoryStream stream)
   at TournamentAssistantShared.PacketWrapper.FromBytes(Byte[] bytes)
   at TournamentAssistantShared.Sockets.Server.ReceiveLoop(ConnectedUser player)
```
```
Invalid wire-type (Varint); this usually means you have over-written a file without truncating or setting the length; see https://stackoverflow.com/q/2152978/23354
   at ProtoBuf.ProtoReader.State.ThrowProtoException(String message)
   at ProtoBuf.ProtoReader.State.ThrowWireTypeException()
   at ProtoBuf.ProtoReader.State.StartSubItem()
   at ProtoBuf.ProtoReader.State.ReadMessage[TSerializer,T](SerializerFeatures features, T value, TSerializer& serializer)
   at proto_2(State& , Packet )
   at ProtoBuf.ProtoReader.State.ReadAsRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.ProtoReader.State.DeserializeRoot[T](T value, ISerializer`1 serializer)
   at ProtoBuf.Serializer.Deserialize[T](Stream source)
   at TournamentAssistantShared.Utilities.ProtobufExtensions.ProtoDeserialize[T](Byte[] data)
   at TournamentAssistantShared.PacketWrapper.FromStream(MemoryStream stream)
   at TournamentAssistantShared.PacketWrapper.FromBytes(Byte[] bytes)
   at TournamentAssistantShared.Sockets.Server.ReceiveLoop(ConnectedUser player)
   ```

I the server ran without connecting anything to the overlay-port, and the only use was connecting to the server through TournamentAssistant 0.6.0 in-game. (Running the Windows-version of the server)

I also ran into the issue of people being locked in the match-room, even though the coordinator closed the room.
I'm trying to get my hands on the players log-files ^^

**Comment by MatrikMoon** [comment]
Howdy! We have since talked on discord and improved the TS client. Are you still having these issues?

**Comment by ThaNightHawk** [comment]
Heyo! From testing, it doesn't look like any errors are coming out of it 😄

**Comment by MatrikMoon** [comment]
Sweet! Closing this, then
